### ISSUE TITLE
Update codebase for SS4

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-agencyextensions#1]
Use namespace `?`. (TBC) - either `CWP\AgencyExtensions` ~~or `SilverStripe\CWPAgencyExtensions`~~ cc @tractorcow 

Sub-tasks can be added separately or as items in a checklist on this issue.

**Comment by tractorcow** [comment]
`cwp` is still the vendor in composer, so I would use this with your namespace also.

**Comment by robbieaverill** [comment]
Resolved in #4
