### ISSUE TITLE
TinyMCE icon picker

### ISSUE THREAD

**Issue by jalamanderman** [silverstripe/cwp-agencyextensions#106]
Is it possible to have the TinyMCE Icon picker in the latest version of this module?

Apologies, it's not totally clear to me what changes were made here / what I need to do. Thanks!

https://github.com/silverstripe/cwp-agencyextensions/blob/310a0b5657e20de488b3e15e8c7da30cdabf036d/_config.php#L9

**Comment by GuySartorelli** [comment]
Hi,

Thank you for your query, however we don't offer support in the issue tracker.

Please review the section in the [Silverstripe CMS 5.0.0 changelog](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#cwp-agency-extensions) about this. If that doesn't fully answer your question, please ask for further help in one of the [community channels](https://www.silverstripe.org/community/)
