### ISSUE TITLE
CarouselPageExtension prevents history from being viewed on a BaseHomePage Subclass.

### ISSUE THREAD

**Issue by caffeineinc** [silverstripe/cwp-agencyextensions#11]
If the CarouselPageExtension is applied and the history is previewed for the Homepage, the Gridfield can't be transformed to readonly due to an exception:

```[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'forTemplate' does not exist on 'SilverStripe\ORM\HasManyList'```

If this extension is removed via `BaseHomePage::remove_extension(CarouselPageExtension::class);`  It works correctly.

**Comment by dhensby** [comment]
Possibly a bug with gridfield instead of this module?

**Comment by dhensby** [comment]
I think the readonly gridfield is trying to render the `CarouselItems` in the template and that's not possible, if that's not a problem for non-readonly gridfields, then I think it's a problem with GridField not knowing how to deal with SS_List objects in readonly mode

According to https://github.com/silverstripe/silverstripe-framework/issues/3357 readonly gridfields don't work anyway :/

**Comment by robbieaverill** [comment]
I've retested this on CWP 2.2.0-rc1 and it doesn't throw any errors any more (https://github.com/silverstripe/silverstripe-framework/issues/3357 is fixed now). It doesn't show anything useful for the history of the carousel GridField, but I think that should also be resolved as a core issue. Feel free to reopen if you disaggree @caffeineinc =)
