### ISSUE TITLE
Site tagline cannot be empty when theme color picker is enabled

### ISSUE THREAD

**Issue by scott1702** [silverstripe/cwp-agencyextensions#14]
When enabling the theme color picker, if a site has an empty tagline and clicks 'Save' in the settings area the site tagline is populated with 'your tagline here'. Culprit is [here](https://github.com/silverstripe/cwp-agencyextensions/blob/master/src/Extensions/CWPSiteConfigExtension.php#L557)

**Comment by robbieaverill** [comment]
I think I'm going to close this as "wont fix". The siteconfig module really needs to distinguish between null and an empty value that has been saved deliberately before it populates its default value.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/cwp-agencyextensions/pull/17

**Comment by ScopeyNZ** [comment]
Closed by #17 .
