### ISSUE TITLE
Label description for the Facebook social media field in SiteConfig doesn't wrap, pushes off screen

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-agencyextensions#18]
**Version: CWP 2.2.0-rc1**

![image](https://user-images.githubusercontent.com/5170590/49093640-caed4980-f264-11e8-9357-42533d4f9450.png)

The text doesn't break, so makes the form horizontally scrollable. I guess for now we should make it wrap.

**Comment by robbieaverill** [comment]
I might suggest we change this to a description or something instead of a right title

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/cwp/pull/176

**Comment by ScopeyNZ** [comment]
Closed in silverstripe/cwp#176
