### ISSUE TITLE
CarouseiIItem should not have a relationship to HomePage

### ISSUE THREAD

**Issue by mxmclaudel** [silverstripe/cwp-agencyextensions#21]
The class CarouselItem has a $has_one relationship with 'HomePage', it should be BaseHomePage::class. The other side of the relationship is defined in CarouselPageExtension which is an extension to CWP's BaseHomePage class.
This is preventing namespacing the HomePage

**Comment by robbieaverill** [comment]
Thanks for the fix @mxmclaudel
