### ISSUE TITLE
Update TinyMCE icons plugin to work with v4

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-agencyextensions#3]
As part with #1 the current setup for the button to add a fontawesome icon to the editor content body is reliant on a now removed API (`tiny_mce_popup`). The good news is that this functionality was moved to a TinyMCE provided compatibility wrapper plugin called `compat3x`. The bad news is that this wrapper doesn't work in the slightest.

In an ideal world we should update the plugin or use an existing one with a compatible licence from the interwebs at large (such as https://github.com/josh18/TinyMCE-FontAwesome-Plugin with MIT). In the very least we need to patch up the current status quo to be functional.

Currently I can get a dialog to show (i.e. with respect to `resource` _exposure_, etc.), but `tinymce.dom.DOMUtils` gives errors that prevents functionality from going any further. It seems that the compatibility code is simply more of a dump & rot :/

http://archive.tinymce.com/forum/viewtopic.php?pid=106605#p106605
>We stuck all old 3.x dialog js files into compat3x but haven't worked on them much.

With regards to updating what we have, I managed to get around the createInstance issue, however the object returned from https://www.tinymce.com/docs/api/tinymce.dom/tinymce.dom.domutils/#domutils doesn't seem to match the documentation, more specifically that a later `bind` then fails, or an internal `fixDoc` when I try to use `call` to get around that.

```
tinymce-cwp-a03eb267a1.js:formatted:4275 Uncaught TypeError: g.fixDoc is not a function
    at Object.o [as DOMUtils] (tinymce-cwp-a03eb267a1.js:formatted:4275)
    at Object.init (VM4523 tiny_mce_popup.js:56)
    at VM4523 tiny_mce_popup.js:483
o @ tinymce-cwp-a03eb267a1.js:formatted:4275
init @ VM4523 tiny_mce_popup.js:56
(anonymous) @ VM4523 tiny_mce_popup.js:483
VM4525 icon.js:7 Uncaught TypeError: Cannot read property 'add' of undefined
    at VM4525 icon.js:7
```

**Comment by robbieaverill** [comment]
Resolved in #4
