### ISSUE TITLE
Publish SiteConfig related images on save

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-agencyextensions#5]
E.g. the `Logo` and `FooterLogo` will not show without first being published, and at current `SiteConfig` is not performing this action. Check the extension that applies these relations also adds an `owns`, and that `SiteConfig` performs a recursive publish (or is `Versioned`) when saved/published.

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-siteconfig/issues/1

For now we should add an onAfterWrite hook for publishing these associated images when you save a SiteConfig record.
